/*
 * grafeas.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AliasContextKind;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * An alias to a repo revision.
 */
@Schema(description = "An alias to a repo revision.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-08-12T17:39:58.649+10:00[Australia/Sydney]")
public class SourceAliasContext {
  @SerializedName("kind")
  private AliasContextKind kind = null;

  @SerializedName("name")
  private String name = null;

  public SourceAliasContext kind(AliasContextKind kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @Schema(description = "")
  public AliasContextKind getKind() {
    return kind;
  }

  public void setKind(AliasContextKind kind) {
    this.kind = kind;
  }

  public SourceAliasContext name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The alias name.
   * @return name
  **/
  @Schema(description = "The alias name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SourceAliasContext sourceAliasContext = (SourceAliasContext) o;
    return Objects.equals(this.kind, sourceAliasContext.kind) &&
        Objects.equals(this.name, sourceAliasContext.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SourceAliasContext {\n");
    
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
