/*
 * grafeas.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PackageVersion;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * An occurrence of a particular package installation found within a system&#x27;s filesystem. E.g., glibc was found in &#x60;/var/lib/dpkg/status&#x60;.
 */
@Schema(description = "An occurrence of a particular package installation found within a system's filesystem. E.g., glibc was found in `/var/lib/dpkg/status`.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-08-12T17:39:58.649+10:00[Australia/Sydney]")
public class V1beta1packageLocation {
  @SerializedName("cpeUri")
  private String cpeUri = null;

  @SerializedName("version")
  private PackageVersion version = null;

  @SerializedName("path")
  private String path = null;

  public V1beta1packageLocation cpeUri(String cpeUri) {
    this.cpeUri = cpeUri;
    return this;
  }

   /**
   * Required. The CPE URI in [CPE format](https://cpe.mitre.org/specification/) denoting the package manager version distributing a package.
   * @return cpeUri
  **/
  @Schema(description = "Required. The CPE URI in [CPE format](https://cpe.mitre.org/specification/) denoting the package manager version distributing a package.")
  public String getCpeUri() {
    return cpeUri;
  }

  public void setCpeUri(String cpeUri) {
    this.cpeUri = cpeUri;
  }

  public V1beta1packageLocation version(PackageVersion version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @Schema(description = "")
  public PackageVersion getVersion() {
    return version;
  }

  public void setVersion(PackageVersion version) {
    this.version = version;
  }

  public V1beta1packageLocation path(String path) {
    this.path = path;
    return this;
  }

   /**
   * The path from which we gathered that this package/version is installed.
   * @return path
  **/
  @Schema(description = "The path from which we gathered that this package/version is installed.")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1packageLocation v1beta1packageLocation = (V1beta1packageLocation) o;
    return Objects.equals(this.cpeUri, v1beta1packageLocation.cpeUri) &&
        Objects.equals(this.version, v1beta1packageLocation.version) &&
        Objects.equals(this.path, v1beta1packageLocation.path);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpeUri, version, path);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1packageLocation {\n");
    
    sb.append("    cpeUri: ").append(toIndentedString(cpeUri)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
